/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MochilaRouteImport } from './routes/mochila'
import { Route as MestreRouteImport } from './routes/mestre'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as CofrinhoRouteImport } from './routes/cofrinho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as FaseStageIdPraticaRouteImport } from './routes/fase.$stageId.pratica'
import { Route as FaseStageIdConteudoRouteImport } from './routes/fase.$stageId.conteudo'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MochilaRoute = MochilaRouteImport.update({
  id: '/mochila',
  path: '/mochila',
  getParentRoute: () => rootRouteImport,
} as any)
const MestreRoute = MestreRouteImport.update({
  id: '/mestre',
  path: '/mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const CofrinhoRoute = CofrinhoRouteImport.update({
  id: '/cofrinho',
  path: '/cofrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FaseStageIdPraticaRoute = FaseStageIdPraticaRouteImport.update({
  id: '/fase/$stageId/pratica',
  path: '/fase/$stageId/pratica',
  getParentRoute: () => rootRouteImport,
} as any)
const FaseStageIdConteudoRoute = FaseStageIdConteudoRouteImport.update({
  id: '/fase/$stageId/conteudo',
  path: '/fase/$stageId/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cofrinho': typeof CofrinhoRoute
  '/loja': typeof LojaRoute
  '/mestre': typeof MestreRoute
  '/mochila': typeof MochilaRoute
  '/ranking': typeof RankingRoute
  '/api/chat': typeof ApiChatRoute
  '/fase/$stageId/conteudo': typeof FaseStageIdConteudoRoute
  '/fase/$stageId/pratica': typeof FaseStageIdPraticaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cofrinho': typeof CofrinhoRoute
  '/loja': typeof LojaRoute
  '/mestre': typeof MestreRoute
  '/mochila': typeof MochilaRoute
  '/ranking': typeof RankingRoute
  '/api/chat': typeof ApiChatRoute
  '/fase/$stageId/conteudo': typeof FaseStageIdConteudoRoute
  '/fase/$stageId/pratica': typeof FaseStageIdPraticaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cofrinho': typeof CofrinhoRoute
  '/loja': typeof LojaRoute
  '/mestre': typeof MestreRoute
  '/mochila': typeof MochilaRoute
  '/ranking': typeof RankingRoute
  '/api/chat': typeof ApiChatRoute
  '/fase/$stageId/conteudo': typeof FaseStageIdConteudoRoute
  '/fase/$stageId/pratica': typeof FaseStageIdPraticaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cofrinho'
    | '/loja'
    | '/mestre'
    | '/mochila'
    | '/ranking'
    | '/api/chat'
    | '/fase/$stageId/conteudo'
    | '/fase/$stageId/pratica'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cofrinho'
    | '/loja'
    | '/mestre'
    | '/mochila'
    | '/ranking'
    | '/api/chat'
    | '/fase/$stageId/conteudo'
    | '/fase/$stageId/pratica'
  id:
    | '__root__'
    | '/'
    | '/cofrinho'
    | '/loja'
    | '/mestre'
    | '/mochila'
    | '/ranking'
    | '/api/chat'
    | '/fase/$stageId/conteudo'
    | '/fase/$stageId/pratica'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CofrinhoRoute: typeof CofrinhoRoute
  LojaRoute: typeof LojaRoute
  MestreRoute: typeof MestreRoute
  MochilaRoute: typeof MochilaRoute
  RankingRoute: typeof RankingRoute
  ApiChatRoute: typeof ApiChatRoute
  FaseStageIdConteudoRoute: typeof FaseStageIdConteudoRoute
  FaseStageIdPraticaRoute: typeof FaseStageIdPraticaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mochila': {
      id: '/mochila'
      path: '/mochila'
      fullPath: '/mochila'
      preLoaderRoute: typeof MochilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mestre': {
      id: '/mestre'
      path: '/mestre'
      fullPath: '/mestre'
      preLoaderRoute: typeof MestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cofrinho': {
      id: '/cofrinho'
      path: '/cofrinho'
      fullPath: '/cofrinho'
      preLoaderRoute: typeof CofrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fase/$stageId/pratica': {
      id: '/fase/$stageId/pratica'
      path: '/fase/$stageId/pratica'
      fullPath: '/fase/$stageId/pratica'
      preLoaderRoute: typeof FaseStageIdPraticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fase/$stageId/conteudo': {
      id: '/fase/$stageId/conteudo'
      path: '/fase/$stageId/conteudo'
      fullPath: '/fase/$stageId/conteudo'
      preLoaderRoute: typeof FaseStageIdConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CofrinhoRoute: CofrinhoRoute,
  LojaRoute: LojaRoute,
  MestreRoute: MestreRoute,
  MochilaRoute: MochilaRoute,
  RankingRoute: RankingRoute,
  ApiChatRoute: ApiChatRoute,
  FaseStageIdConteudoRoute: FaseStageIdConteudoRoute,
  FaseStageIdPraticaRoute: FaseStageIdPraticaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
